name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Infrastructure
        run: terraform plan

      - name: Apply Infrastructure
        run: terraform apply -auto-approve

        - name: Validate Terraform
        run: terraform validate

        - name: Format Check
        run: terraform fmt -check

